# Generated by Django 5.2.7 on 2025-11-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogindex_homepage_featured_services_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesection',
            name='category',
        ),
    ]
