# Generated by Django 5.2.7 on 2025-11-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_servicesection_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
