# Generated by Django 5.2.7 on 2025-11-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_service_duration_remove_service_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемая услуга'),
        ),
    ]
