# Generated by Django 5.2.7 on 2025-11-04 08:19

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_service_featured'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Описание героя'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Изображение героя'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Заголовок героя'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='featured_services_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Описание рекомендуемых услуг'),
        ),
    ]
